name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      STRIPE_PAYOUT_ACCOUNT_ID: ${{ secrets.STRIPE_PAYOUT_ACCOUNT_ID }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client
        pip install streamlit
        pip install stripe

    - name: Run Streamlit App
      run: |
        streamlit run src/scripts/youtube_dashboard.py
